### PR TITLE
Install BasisOfExternalHom & CoefficientsOfMorphism as primitive methods to improve performance

### PR DESCRIPTION
**Pull request by kamalsaleh**

### CODE REVIEW

**Review by mohamed-barakat — APPROVED** [review]
Look good. Thanks.

Does it increase the performance of YonedaEmbedding?

**Comment by kamalsaleh** [comment]
The Yoneda embedding functor relies only on the `HomStructure` operations, so this PR plays almost no role for it. This PR  is intended to increase performance of these two operations themselves (since the current general derivation of them is general and require a lot more computation and overhead
https://github.com/homalg-project/CAP_project/blob/cddfb2cbdfb0b541c3a0b0b44f77a574c0ad5625/CAP/gap/DerivedMethods.gi#L3450-L3474,
 and beside that the caching in `Algebroids` is disabled). This also improves other operations, such as `CoverElementByProjectiveObject` in
https://github.com/kamalsaleh/FunctorCategories/blob/9828d2450520bc952f0aff1922d5ea5de754cbb6/gap/HomologicalMethods.gi#L72

**Comment by mohamed-barakat** [comment]
OK, thanks for the clarification. I have converted the PR into a draft PR.

**Comment by mohamed-barakat** [comment]
Sorry, I got confused with your other commit message. I will merge this PR.

**Pull request merged**
