### PR TITLE
comply with CompilerForCAP v2022.05-11

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
@zickgraf: This diff looks suspicious to me. It is best viewed ignoring whitespaces.

**Comment by zickgraf** [comment]
Indeed. I don't think this has anything to do with CompilerForCAP: The two argument version of UnionOfRows is used instead of the list version. Are there any recent changes of some package using UnionOfRows? It could also be caused by a different derivation being triggered. I can investigate on Monday, if you don't need the Algebroid CI over the weekend, please don't merge.

**Comment by zickgraf** [comment]
Ah, the CI is failing. Do you have some local changes involving UnionOfRows? I cannot reproduce locally right now because some weird errors pop up.

**Comment by mohamed-barakat** [comment]
Yes, some dangling stuff to beautify the output for the talk :) I need a monorepo :)

**Comment by zickgraf** [comment]
> Yes, some dangling stuff to beautify the output for the talk :) I need a monorepo :)

Aaah, I see. I was a bit shocked seeing unexpected compilation results on a Friday evening, I explicitly test Algebroids (and others) before every major PR to CompilerForCAP to avoid such surprises :D

**Pull request closed without merging**
