### PR TITLE
Adjust to CompilerForCAP 2021.11-02

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
There seems to be an issue with the generated code -> I will mark this PR as a draft until I have found the cause.

**Comment by zickgraf** [comment]
The issue is fixed by https://github.com/homalg-project/CAP_project/pull/735.

**Comment by zickgraf** [comment]
Note that due to https://github.com/homalg-project/CAP_project/commit/7209b9086b83f9766e2ebc1b7913b65066b5870e we do not have to add the zero of the underlying algebra as an attribute to the category anymore.

**Comment by mohamed-barakat** [comment]
I need to talk to you about this PR, we can do this tomorrow.

**Review by mohamed-barakat — APPROVED** [review]
Approved after discussion with Fabain. Thank you very much.

**Pull request merged**
