### PR TITLE
Import QuiverRows from FreydCategoriesForCAP

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
Note: To avoid a dependency on https://github.com/homalg-project/CAP_project/pull/1208, QuiverRows in this PR only gets loaded if it has not been loaded by FreydCategoriesForCAP before -> the coverage information is not accurate. Once this PR is merged, I will merge https://github.com/homalg-project/CAP_project/pull/1208 and then create a new PR here removing the conditional loading mechanism.

**Comment by zickgraf** [comment]
The errors are due to FunctorCategories.

**Comment by zickgraf** [comment]
As I had hoped, this decreases the runtime of the CI noticeably.

**Comment by mohamed-barakat** [comment]
> As I had hoped, this decreases the runtime of the CI noticeably.

Thank you very much.

**Pull request merged**
