### PR TITLE
Install LaTeXOutput operations

### PR DESCRIPTION
**Pull request by kamalsaleh**
This PR Depends on https://github.com/sunnyquiver/QPA2/pull/39

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Thank you very much kamal.

I there a place where I can see the effect?

I have two minor thoughts/suggestions:

1. Oyvind won't probably like the idea of increasing QPA2 versions from 2.0 to 2.1, which could delay a merge. Since QPA2 is in the permanent dev-state it is OK if we do not increase the dependency.

2. Please replace `LaTeXOutput` with `LaTeXStringOp`. If in the future `LaTeXString` becomes an operation we can then drop the `Op`.

**Comment by kamalsaleh** [comment]
>     1. Oyvind won't probably like the idea of increasing QPA2 versions from 2.0 to 2.1, which could delay a merge. Since QPA2 is in the permanent dev-state it is OK if we do not increase the dependency.

Increasing the version was just a force of habit; and you are right, the last time `QPA2`-version was changed is in 2015. Anyway, thanks to Oyvind, the PR has already been merged.


>     2\. Please replace `LaTeXOutput` with `LaTeXStringOp`. If in the future `LaTeXString` becomes an operation we can then drop the `Op`.

Here I was following the convention of `CAP`, which is until now `LaTeXOutput`. If you agree, I can replace the names by `LaTeXStringOp`; then let `LaTeXOutput` delegate to `LaTeXStringOp`, so that we have all operations working.

A quick way to view the latex string would be to use the command `ShowLaTeXString` which I installed in `ComplexesCategories`, which creates a temporarily .tex file and compiles it.

Example in Gap:

```
LoadPackage( "Algebroids" );
Q := RightQuiver( "Q(3)[alpha:1->2,beta:2->3,gamma:1->3]" );
SetLabelsAsLaTeXStrings( Q, 
            [ "V_1", "V_2", "V_3" ],
            [ "\\alpha", "\\beta", "\\gamma" ]
          );
kQ := PathAlgebra( HomalgFieldOfRationals(), Q );
algebroid := Algebroid( kQ );
f := PreCompose( algebroid.alpha, algebroid.beta ) - algebroid.gamma;
ShowLaTeXString( LaTeXOutput( f : OnlyDatum := true )  );
ShowLaTeXString( LaTeXOutput( f )  );

```

In a Jupyter notebook
```
using HomalgProject
using LaTeXStrings
LoadPackage( "Algebroids" )
Q = RightQuiver( julia_to_gap( "Q(3)[alpha:1->2,beta:2->3,gamma:1->3]" ) )
SetLabelsAsLaTeXStrings( Q, 
            julia_to_gap( [ g"V_1", g"V_2", g"V_3" ] ),
            julia_to_gap( [ g"\alpha", g"\beta", g"\gamma" ] )
          )
kQ = PathAlgebra( HomalgFieldOfRationals(), Q )
algebroid = Algebroid( kQ )
f = PreCompose( algebroid.alpha, algebroid.beta ) - 2 * algebroid.gamma
latexstring( LaTeXOutput( f ) )
latexstring( LaTeXOutput( f, OnlyDatum = true ) )
```

**Comment by mohamed-barakat** [comment]
> Increasing the version was just a force of habit; and you are right, the last time `QPA2`-version was changed is in 2015. Anyway, thanks to Oyvind, the PR has already been merged.

Excellent. Could you then please increase the version on QPA2 here?

**Comment by kamalsaleh** [comment]
> Excellent. Could you then please increase the version on QPA2 here?

Sorry, the commit is not there anymore :)

**Comment by mohamed-barakat** [comment]
> Sorry, the commit is not there anymore :)

No problem

**Comment by mohamed-barakat** [comment]
> Here I was following the convention of `CAP`, which is until now `LaTeXOutput`. If you agree, I can replace the names by `LaTeXStringOp`; then let `LaTeXOutput` delegate to `LaTeXStringOp`, so that we have all operations working.

I do not like the CAP convention and if you do not depend on it I would prefer to switch to `LaTeXStringOp`.

**Comment by mohamed-barakat** [comment]
One more comment: Could you please assign the quiver to `q` instead of `Q` so that we do not get `Q * Q` in the output?

**Comment by mohamed-barakat** [comment]
> A quick way to view the latex string would be to use the command `ShowLaTeXString` which I installed in `ComplexesCategories`, which creates a temporarily .tex file and compiles it.
> 
> Example in Gap:
> 
> ```
> LoadPackage( "Algebroids" );
> Q := RightQuiver( "Q(3)[alpha:1->2,beta:2->3,gamma:1->3]" );
> SetLabelsAsLaTeXStrings( Q, 
>             [ "V_1", "V_2", "V_3" ],
>             [ "\\alpha", "\\beta", "\\gamma" ]
>           );
> kQ := PathAlgebra( HomalgFieldOfRationals(), Q );
> algebroid := Algebroid( kQ );
> f := PreCompose( algebroid.alpha, algebroid.beta ) - algebroid.gamma;
> ShowLaTeXString( LaTeXOutput( f : OnlyDatum := true )  );
> ShowLaTeXString( LaTeXOutput( f )  );
> ```

Works, thank you very much.

**Comment by kamalsaleh** [comment]
> > Here I was following the convention of `CAP`, which is until now `LaTeXOutput`. If you agree, I can replace the names by `LaTeXStringOp`; then let `LaTeXOutput` delegate to `LaTeXStringOp`, so that we have all operations working.
> 
> I do not like the CAP convention and if you do not depend on it I would prefer to switch to `LaTeXStringOp`.

The main use will be to have a nice latex output for additive closures and then for complexes and homotopy categories. Any generic latex-method for additive closures will require the `CAP` convention. Hence I suggest installing both. One delegates to the other.

**Comment by mohamed-barakat** [comment]
> The main use will be to have a nice latex output for additive closures and then for complexes and homotopy categories. Any generic latex-method for additive closures will require the `CAP` convention. Hence I suggest installing both. One delegates to the other.

I see. Then I agree with your solution. Could you please update the PR?

**Comment by mohamed-barakat** [comment]
> In a Jupyter notebook
> 
> ```
> using HomalgProject
> using LaTeXStrings
> LoadPackage( "Algebroids" )
> Q = RightQuiver( julia_to_gap( "Q(3)[alpha:1->2,beta:2->3,gamma:1->3]" ) )
> SetLabelsAsLaTeXStrings( Q, 
>             julia_to_gap( [ g"V_1", g"V_2", g"V_3" ] ),
>             julia_to_gap( [ g"\alpha", g"\beta", g"\gamma" ] )
>           )
> kQ = PathAlgebra( HomalgFieldOfRationals(), Q )
> algebroid = Algebroid( kQ )
> f = PreCompose( algebroid.alpha, algebroid.beta ) - 2 * algebroid.gamma
> latexstring( LaTeXOutput( f ) )
> latexstring( LaTeXOutput( f, OnlyDatum = true ) )
> ```

I don't quite understand how you depend on the package `LaTeXStrings` but I would like to avoid this dependency as far as possible.

**Comment by kamalsaleh** [comment]
I don't depend on `LaTeXStrings` now, it was only a quick way to view strings in jupyter. I think I will use the same way you use in the package `GradedCategories`.

**Comment by kamalsaleh** [comment]
I have already updated the PR

**Comment by mohamed-barakat** [comment]
Sorry, could you please rebase and push again?

**Comment by kamalsaleh** [comment]
Done!

**Comment by mohamed-barakat** [comment]
Thank you very much Kamal.

**Pull request merged**
